[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.0"
lazy_static = "1.4.0"

[dependencies.bevy]
# version = "0.9"
git = "https://github.com/bevyengine/bevy"
branch = "main"
features = [
    "bmp",
    "wav"
]